name: Shell script linting

on:
  pull_request:
    types: [opened, synchronize]
    paths: '**.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: ludeeus/action-shellcheck@0.5.0
      with:
        fetch-depth: 0

